apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::834091598690:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-D8I5SN0DCC6S
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::834091598690:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-21T10:07:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1693"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 080470a6-dca4-474f-b5d5-4b9797f28605
